In [74]:
import pandas as pd
import kamping
import numpy as np
from kamping.data.dataset import MetaboliteProteinInteraction

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [26]:
mpi = pd.read_csv('../data/string_stitch/raw/9606.protein_chemical.links.v5.0.tsv', sep='\t')
unique_compounds = mpi['chemical'].unique()
unique_compounds

array(['CIDm91758680', 'CIDm91758408', 'CIDm91758407', ...,
       'CIDs00000004', 'CIDs00000003', 'CIDs00000001'], dtype=object)

In [32]:
import pandas as pd

# Read the unique compounds from the second TSV file
mpi = pd.read_csv('../data/string_stitch/raw/9606.protein_chemical.links.v5.0.tsv', sep='\t')
unique_compounds = mpi['chemical'].unique()

# Initialize an empty DataFrame to store the filtered data
filtered_smiles = pd.DataFrame()

# Define the chunk size
chunk_size = 1000000  # Adjust based on your memory capacity

# Read the first TSV file in chunks
for chunk in pd.read_csv('../data/string_stitch/raw/chemicals.v5.0.tsv', sep='\t', chunksize=chunk_size):
    # Filter the chunk based on unique_compounds
    filtered_chunk = chunk[chunk['chemical'].isin(unique_compounds)]
    # Append the filtered chunk to the filtered_smiles DataFrame
    filtered_smiles = pd.concat([filtered_smiles, filtered_chunk], ignore_index=True)

# Now filtered_smiles contains the filtered data

KeyboardInterrupt:

In [29]:
# Save the filtered data to a new TSV file
filtered_smiles.to_csv('../data/string_stitch/raw/filtered_output.tsv', sep='\t', index=False)

In [30]:
# import the smile strings
smiles = pd.read_csv('../data/string_stitch/raw/filtered_output.tsv', sep='\t', usecols=['chemical', 'SMILES_string'], index_col='chemical')
smiles

                                                 SMILES_string
chemical
CIDs00000001                  CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C
CIDs00000003                          C1=CC(C(C(=C1)C(=O)O)O)O
CIDs00000004                                           CC(CN)O
CIDs00000005                              C(C(=O)COP(=O)(O)O)N
CIDs00000006         C1=CC(=C(C=C1[N+](=O)[O-])[N+](=O)[O-])Cl
...                                                        ...
CIDm91758404                  C1CCC(CC1)COC2=CC=CC(=C2)C(CCO)O
CIDm91758406          C1COCCC1NC2=NC=C3CCN(CC3=N2)S(=O)(=O)CCS
CIDm91758407       CNC(=O)C1=CC=CC=C1NC2=CC(=NC=C2Cl)NC3CCOCC3
CIDm91758408   C1COCCC1NC2=NC=C(C(=N2)NC3=CC=CC=C3NC(=O)CCS)Cl
CIDm91758680  C(C(=O)[O-])C(CC(=O)[O-])(C(=O)[O-])O.N.O.[Fe+3]

[786494 rows x 1 columns]

In [38]:
from rdkit import Chem

mols = []

for compound in unique_compounds:
    # check if the compound exists in the smiles DataFrame
    if compound in smiles.index:
        # convert the SMILES string to a RDKit molecule object
        mols.append(Chem.MolFromSmiles(smiles.loc[compound, 'SMILES_string']))
    else:
        # if the compound does not exist, append None
        print(f'{compound} not found')
        mols.append(None)
    # create a pd.DataFrame
ROMols = pd.DataFrame({'id': list(unique_compounds), 'ROMol': mols})
# remove the None values
ROMols = ROMols.dropna()

[16:18:17] WARNING: not removing hydrogen atom without neighbors
[16:18:18] WARNING: not removing hydrogen atom without neighbors
[16:18:18] WARNING: not removing hydrogen atom without neighbors
[16:18:18] WARNING: not removing hydrogen atom without neighbors

CIDm73330332 not found

[16:18:18] WARNING: not removing hydrogen atom without neighbors
[16:18:19] WARNING: not removing hydrogen atom without neighbors
[16:18:19] WARNING: not removing hydrogen atom without neighbors

CIDm70678717 not found

[16:18:20] WARNING: not removing hydrogen atom without neighbors
[16:18:20] WARNING: not removing hydrogen atom without neighbors

CIDm44237211 not found
CIDm44237133 not found
CIDm25098796 not found

[16:18:30] Explicit valence for atom # 1 Cl, 3, is greater than permitted
[16:18:31] WARNING: not removing hydrogen atom without neighbors
[16:18:31] WARNING: not removing hydrogen atom without neighbors
[16:18:31] WARNING: not removing hydrogen atom without neighbors
[16:18:31] WARNING: not removing hydrogen atom without neighbors
[16:18:31] WARNING: not removing hydrogen atom without neighbors
[16:18:31] WARNING: not removing hydrogen atom without neighbors
[16:18:31] WARNING: not removing hydrogen atom without neighbors
[16:18:31] WARNING: not removing hydrogen atom without neighbors
[16:18:31] WARNING: not removing hydrogen atom without neighbors
[16:18:32] WARNING: not removing hydrogen atom without neighbors
[16:18:32] WARNING: not removing hydrogen atom without neighbors
[16:18:32] WARNING: not removing hydrogen atom without neighbors
[16:18:32] WARNING: not removing hydrogen atom without neighbors
[16:18:32] WARNING: not removing hydrogen atom without neighbors
[16:18:32] WARNING: not removing hydrogen atom without neighbors
[16:18:32] WARNING: not removing hydrogen atom without neighbors
[16:18:32] WARNING: not removing hydrogen atom without neighbors
[16:18:32] WARNING: not removing hydrogen atom without neighbors
[16:18:32] WARNING: not removing hydrogen atom without neighbors
[16:18:32] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] Explicit valence for atom # 7 Br, 3, is greater than permitted
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:39] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] Explicit valence for atom # 1 Cl, 3, is greater than permitted

CIDm05189703 not found

[16:18:40] Explicit valence for atom # 7 Cl, 5, is greater than permitted
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors
[16:18:40] WARNING: not removing hydrogen atom without neighbors

CIDm03080603 not found

[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] Explicit valence for atom # 25 Cl, 3, is greater than permitted
[16:18:41] Explicit valence for atom # 26 Cl, 3, is greater than permitted
[16:18:41] Explicit valence for atom # 44 Cl, 3, is greater than permitted
[16:18:41] Explicit valence for atom # 10 Cl, 3, is greater than permitted
[16:18:41] Explicit valence for atom # 10 Cl, 3, is greater than permitted
[16:18:41] Explicit valence for atom # 21 Cl, 3, is greater than permitted
[16:18:41] Explicit valence for atom # 18 Cl, 3, is greater than permitted
[16:18:41] Explicit valence for atom # 22 Cl, 3, is greater than permitted
[16:18:41] Explicit valence for atom # 25 Cl, 3, is greater than permitted
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:41] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] Explicit valence for atom # 1 Cl, 2, is greater than permitted
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:42] WARNING: not removing hydrogen atom without neighbors
[16:18:43] WARNING: not removing hydrogen atom without neighbors
[16:18:43] Explicit valence for atom # 1 I, 7, is greater than permitted
[16:18:43] WARNING: not removing hydrogen atom without neighbors
[16:18:43] WARNING: not removing hydrogen atom without neighbors
[16:18:43] WARNING: not removing hydrogen atom without neighbors
[16:18:43] WARNING: not removing hydrogen atom without neighbors
[16:18:43] Explicit valence for atom # 1 Br, 3, is greater than permitted
[16:18:43] Explicit valence for atom # 1 Si, 8, is greater than permitted
[16:18:43] WARNING: not removing hydrogen atom without neighbors
[16:18:43] WARNING: not removing hydrogen atom without neighbors
[16:18:43] Explicit valence for atom # 1 Si, 8, is greater than permitted
[16:18:43] Explicit valence for atom # 1 Si, 8, is greater than permitted
[16:18:43] Explicit valence for atom # 1 Si, 8, is greater than permitted
[16:18:43] Explicit valence for atom # 1 Cl, 3, is greater than permitted
[16:18:43] Explicit valence for atom # 1 Br, 5, is greater than permitted
[16:18:43] Explicit valence for atom # 1 Br, 3, is greater than permitted
[16:18:43] Explicit valence for atom # 1 Cl, 7, is greater than permitted

CIDm00002828 not found

[16:18:43] WARNING: not removing hydrogen atom without neighbors

CIDs86765263 not found
CIDs86765261 not found
CIDs86301874 not found
CIDs86301872 not found
CIDs86301869 not found
CIDs78225872 not found

[16:18:44] WARNING: not removing hydrogen atom without neighbors
[16:18:45] WARNING: not removing hydrogen atom without neighbors
[16:18:45] WARNING: not removing hydrogen atom without neighbors
[16:18:45] WARNING: not removing hydrogen atom without neighbors

CIDs73330332 not found
CIDs72946434 not found
CIDs72945691 not found
CIDs72735761 not found
CIDs72735760 not found
CIDs72735758 not found
CIDs72735566 not found
CIDs72735565 not found
CIDs72735564 not found
CIDs72735563 not found
CIDs72735562 not found
CIDs72735390 not found
CIDs72735389 not found
CIDs72735387 not found
CIDs72735386 not found
CIDs72735205 not found
CIDs72735204 not found
CIDs72714179 not found
CIDs72713956 not found
CIDs72713510 not found
CIDs72713289 not found
CIDs72713074 not found
CIDs72711590 not found
CIDs72710924 not found
CIDs72374833 not found
CIDs72374714 not found
CIDs72205874 not found
CIDs72191054 not found
CIDs72190752 not found
CIDs72190453 not found
CIDs72163632 not found
CIDs72163630 not found
CIDs72163628 not found
CIDs72163488 not found
CIDs72163350 not found
CIDs72163206 not found
CIDs71770033 not found
CIDs71770032 not found
CIDs71769906 not found
CIDs71769646 not found
CIDs71769414 not found
CIDs71741072 not found
CIDs71741071 not found
CIDs71740828 not found
CIDs71740827 not found

[16:18:45] WARNING: not removing hydrogen atom without neighbors

CIDs71683056 not found
CIDs71659504 not found
CIDs71659502 not found
CIDs71659370 not found
CIDs71659368 not found
CIDs71659366 not found
CIDs71659239 not found
CIDs71659237 not found
CIDs71658875 not found
CIDs71606866 not found
CIDs71606707 not found
CIDs71606706 not found
CIDs71606552 not found
CIDs71606392 not found
CIDs71606219 not found
CIDs71605888 not found
CIDs71605887 not found
CIDs71604690 not found
CIDs71604540 not found
CIDs71562541 not found
CIDs71529222 not found
CIDs71529221 not found
CIDs71529179 not found
CIDs71529176 not found
CIDs71521186 not found
CIDs71521185 not found
CIDs71508527 not found
CIDs71448904 not found
CIDs70789204 not found

[16:18:46] WARNING: not removing hydrogen atom without neighbors
[16:18:46] WARNING: not removing hydrogen atom without neighbors
[16:18:47] WARNING: not removing hydrogen atom without neighbors
[16:18:47] WARNING: not removing hydrogen atom without neighbors
[16:18:47] WARNING: not removing hydrogen atom without neighbors

CIDs60142088 not found
CIDs60142086 not found
CIDs60141946 not found
CIDs60141945 not found
CIDs59149266 not found
CIDs59149264 not found
CIDs59149255 not found

[16:18:47] WARNING: not removing hydrogen atom without neighbors
[16:18:48] WARNING: not removing hydrogen atom without neighbors
[16:18:48] WARNING: not removing hydrogen atom without neighbors

CIDs57414457 not found
CIDs57414324 not found
CIDs57414187 not found
CIDs57414067 not found
CIDs57411574 not found
CIDs57411343 not found
CIDs57411229 not found
CIDs57411228 not found
CIDs57410993 not found
CIDs57410866 not found
CIDs57410865 not found
CIDs57410864 not found
CIDs57410746 not found
CIDs56964800 not found
CIDs56951099 not found
CIDs56951098 not found
CIDs56950973 not found
CIDs56950972 not found
CIDs56851059 not found
CIDs56851058 not found

[16:18:48] WARNING: not removing hydrogen atom without neighbors
[16:18:48] WARNING: not removing hydrogen atom without neighbors

CIDs56643490 not found
CIDs56597627 not found
CIDs56595199 not found
CIDs54757084 not found
CIDs54757083 not found
CIDs54756988 not found
CIDs54753982 not found
CIDs54671631 not found
CIDs54669777 not found
CIDs54669776 not found
CIDs54669775 not found
CIDs53380927 not found
CIDs53372003 not found
CIDs53364015 not found
CIDs53363927 not found
CIDs53363926 not found
CIDs53363844 not found
CIDs53306555 not found
CIDs53306554 not found
CIDs53304513 not found
CIDs53304512 not found
CIDs53304352 not found
CIDs53240405 not found
CIDs51351261 not found
CIDs51351151 not found
CIDs51351008 not found
CIDs51350911 not found
CIDs51350898 not found
CIDs51350897 not found
CIDs51350788 not found
CIDs51350673 not found
CIDs51350661 not found
CIDs51350536 not found
CIDs51350534 not found
CIDs51350533 not found
CIDs51350528 not found
CIDs51350525 not found
CIDs51350398 not found
CIDs51350395 not found
CIDs51350393 not found
CIDs51350127 not found
CIDs51349983 not found
CIDs51349848 not found
CIDs51349711 not found
CIDs51349423 not found
CIDs50922685 not found
CIDs49866574 not found
CIDs49831171 not found
CIDs46911580 not found
CIDs46911579 not found
CIDs46866286 not found
CIDs46866285 not found
CIDs46849666 not found
CIDs46201037 not found
CIDs46187604 not found
CIDs46187603 not found
CIDs46177766 not found
CIDs45272624 not found
CIDs45269220 not found
CIDs44596242 not found
CIDs44550016 not found
CIDs44549766 not found
CIDs44549765 not found
CIDs44549488 not found
CIDs44549358 not found
CIDs44324014 not found
CIDs44324001 not found
CIDs44323977 not found
CIDs44323959 not found
CIDs44323958 not found
CIDs44323954 not found
CIDs44323949 not found
CIDs44323860 not found
CIDs44323845 not found
CIDs44323781 not found
CIDs44323737 not found
CIDs44323736 not found
CIDs44323728 not found
CIDs44323727 not found
CIDs44323726 not found
CIDs44323682 not found
CIDs44323606 not found
CIDs44323584 not found
CIDs44323583 not found
CIDs44323520 not found
CIDs44323433 not found
CIDs44323369 not found
CIDs44275260 not found
CIDs44250320 not found
CIDs44222617 not found
CIDs44221304 not found
CIDs44220879 not found
CIDs44217059 not found
CIDs44187909 not found
CIDs44187908 not found
CIDs44157183 not found
CIDs44157100 not found
CIDs44139868 not found
CIDs44139867 not found
CIDs44139866 not found
CIDs44139864 not found
CIDs44139863 not found
CIDs44139862 not found
CIDs44139858 not found
CIDs44139857 not found
CIDs44139856 not found
CIDs44139855 not found
CIDs44139854 not found
CIDs44139853 not found
CIDs44139852 not found
CIDs44139851 not found
CIDs44139850 not found
CIDs44139849 not found
CIDs44139848 not found
CIDs44139847 not found
CIDs44139846 not found
CIDs44139845 not found
CIDs44139843 not found
CIDs44139842 not found
CIDs44139841 not found
CIDs44139840 not found
CIDs44139716 not found
CIDs44139715 not found
CIDs44139714 not found
CIDs42631387 not found
CIDs42631274 not found
CIDs42631168 not found
CIDs42627296 not found
CIDs42624370 not found
CIDs42624369 not found
CIDs42624359 not found
CIDs42623560 not found
CIDs42623559 not found
CIDs42623480 not found
CIDs25265829 not found
CIDs25242461 not found
CIDs25235992 not found
CIDs25209888 not found
CIDs25199072 not found
CIDs25198923 not found
CIDs25198785 not found
CIDs25198784 not found
CIDs25198783 not found
CIDs25198356 not found
CIDs25198355 not found
CIDs25198221 not found
CIDs25198220 not found
CIDs25198069 not found
CIDs25198067 not found
CIDs25198043 not found
CIDs25197918 not found
CIDs25197917 not found
CIDs25197916 not found
CIDs25192420 not found
CIDs25181073 not found
CIDs25181072 not found
CIDs25181071 not found
CIDs25181070 not found
CIDs25181069 not found
CIDs25181068 not found
CIDs25181067 not found
CIDs25181065 not found
CIDs25181064 not found
CIDs25181062 not found
CIDs25181061 not found
CIDs25181060 not found
CIDs25181059 not found
CIDs25181058 not found
CIDs25181057 not found
CIDs25181056 not found
CIDs25181055 not found
CIDs25181054 not found
CIDs25181053 not found
CIDs25181052 not found
CIDs25181051 not found
CIDs25181050 not found
CIDs25181049 not found
CIDs25181048 not found
CIDs25181047 not found
CIDs25181046 not found
CIDs25181045 not found
CIDs25180486 not found
CIDs25180467 not found
CIDs25180280 not found
CIDs25180086 not found
CIDs25180083 not found
CIDs25179698 not found
CIDs25179696 not found
CIDs25167220 not found
CIDs25167219 not found
CIDs25164611 not found
CIDs25164610 not found
CIDs25164419 not found
CIDs25164418 not found
CIDs25164417 not found
CIDs25164416 not found
CIDs25164216 not found
CIDs25164213 not found
CIDs25164212 not found
CIDs25164211 not found
CIDs25154891 not found
CIDs25149938 not found
CIDs25149935 not found
CIDs25149934 not found
CIDs25149933 not found
CIDs25149932 not found
CIDs25099121 not found
CIDs25089637 not found
CIDs25089633 not found
CIDs25089631 not found
CIDs25088935 not found
CIDs25087621 not found
CIDs25081516 not found
CIDs25079892 not found
CIDs25078294 not found
CIDs25077966 not found
CIDs25056996 not found
CIDs25056483 not found
CIDs25034083 not found
CIDs24995847 not found
CIDs24939264 not found
CIDs24895463 not found
CIDs24895366 not found
CIDs24895267 not found
CIDs24895011 not found
CIDs24894902 not found
CIDs24894654 not found
CIDs24894534 not found
CIDs24894432 not found

[16:19:00] Explicit valence for atom # 1 Cl, 3, is greater than permitted
[16:19:00] WARNING: not removing hydrogen atom without neighbors
[16:19:00] WARNING: not removing hydrogen atom without neighbors
[16:19:00] WARNING: not removing hydrogen atom without neighbors

CIDs23651238 not found
CIDs23631558 not found
CIDs23631557 not found
CIDs23631556 not found
CIDs23631555 not found
CIDs23631472 not found
CIDs23631471 not found
CIDs23631470 not found
CIDs23631469 not found
CIDs23631382 not found
CIDs23631284 not found
CIDs23631281 not found
CIDs23631280 not found
CIDs23631193 not found
CIDs23631192 not found
CIDs23631191 not found
CIDs23631190 not found
CIDs23631189 not found
CIDs23631111 not found
CIDs23631110 not found
CIDs23631109 not found
CIDs23631108 not found
CIDs23625921 not found
CIDs23426696 not found

[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors

CIDs21817991 not found

[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:01] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors

CIDs20338109 not found
CIDs18003260 not found
CIDs17753380 not found
CIDs16750117 not found
CIDs16730342 not found
CIDs16725871 not found
CIDs16720835 not found
CIDs16719450 not found

[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors

CIDs16221238 not found
CIDs16221237 not found
CIDs16221177 not found
CIDs16209969 not found
CIDs16209064 not found
CIDs16201973 not found
CIDs16201684 not found
CIDs16201644 not found
CIDs16201639 not found
CIDs16201615 not found
CIDs16201470 not found
CIDs16201387 not found
CIDs16201346 not found
CIDs16200894 not found
CIDs16199244 not found
CIDs16197894 not found
CIDs16158092 not found
CIDs16157847 not found
CIDs16157571 not found
CIDs16157335 not found
CIDs16156956 not found
CIDs16156950 not found
CIDs16156945 not found
CIDs16156642 not found
CIDs16155357 not found
CIDs16155099 not found
CIDs16154842 not found
CIDs16154839 not found
CIDs16154836 not found
CIDs16154735 not found
CIDs16154724 not found
CIDs16154717 not found
CIDs16154716 not found
CIDs16154622 not found
CIDs16154600 not found
CIDs16154494 not found
CIDs16154492 not found
CIDs16154484 not found
CIDs16154399 not found
CIDs16154392 not found
CIDs16154383 not found
CIDs16154263 not found
CIDs16154139 not found
CIDs16154123 not found
CIDs16154040 not found
CIDs16154036 not found
CIDs16153937 not found
CIDs16153933 not found
CIDs16153810 not found
CIDs16153580 not found
CIDs16153570 not found
CIDs16153566 not found
CIDs16153464 not found
CIDs16153463 not found
CIDs16153459 not found
CIDs16153235 not found
CIDs16153232 not found
CIDs16153231 not found
CIDs16152981 not found
CIDs16152953 not found
CIDs16152886 not found
CIDs16152874 not found
CIDs16152867 not found
CIDs16152757 not found
CIDs16152756 not found
CIDs16152754 not found
CIDs16152602 not found
CIDs16152511 not found
CIDs16152412 not found
CIDs16152291 not found
CIDs16152177 not found
CIDs16152175 not found
CIDs16152174 not found
CIDs16152173 not found
CIDs16152056 not found
CIDs16151963 not found
CIDs16151957 not found
CIDs16151956 not found
CIDs16151955 not found
CIDs16151944 not found
CIDs16151837 not found
CIDs16151832 not found
CIDs16151828 not found
CIDs16151716 not found
CIDs16151614 not found
CIDs16151609 not found
CIDs16151608 not found
CIDs16151605 not found
CIDs16151600 not found
CIDs16151595 not found
CIDs16151594 not found
CIDs16150935 not found
CIDs16150120 not found
CIDs16150118 not found
CIDs16148391 not found
CIDs16148366 not found
CIDs16148331 not found
CIDs16148108 not found
CIDs16148106 not found
CIDs16147801 not found
CIDs16147764 not found
CIDs16147700 not found
CIDs16147483 not found
CIDs16147480 not found
CIDs16147436 not found
CIDs16147387 not found
CIDs16147183 not found
CIDs16146931 not found
CIDs16146930 not found
CIDs16146584 not found
CIDs16146560 not found
CIDs16146516 not found
CIDs16146333 not found
CIDs16146297 not found
CIDs16146247 not found
CIDs16145130 not found
CIDs16145120 not found
CIDs16145055 not found
CIDs16145054 not found
CIDs16144855 not found
CIDs16144579 not found
CIDs16144461 not found
CIDs16144278 not found
CIDs16144255 not found
CIDs16143668 not found
CIDs16143665 not found
CIDs16143584 not found
CIDs16143494 not found
CIDs16143340 not found
CIDs16143224 not found
CIDs16143023 not found
CIDs16142979 not found
CIDs16142905 not found
CIDs16142684 not found
CIDs16142259 not found
CIDs16139319 not found
CIDs16139250 not found
CIDs16139013 not found
CIDs16138864 not found
CIDs16138610 not found
CIDs16138390 not found
CIDs16137976 not found
CIDs16137743 not found
CIDs16136660 not found
CIDs16135979 not found
CIDs16135265 not found
CIDs16133759 not found
CIDs16131090 not found
CIDs16126687 not found

[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors
[16:19:02] WARNING: not removing hydrogen atom without neighbors

CIDs16083051 not found
CIDs16083048 not found
CIDs16083047 not found
CIDs16083039 not found
CIDs16046037 not found
CIDs16046035 not found
CIDs16046034 not found
CIDs16007236 not found
CIDs15942671 not found
CIDs15828268 not found
CIDs12408079 not found
CIDs12071552 not found
CIDs11777383 not found
CIDs10501876 not found
CIDs10392627 not found
CIDs10267087 not found
CIDs10078815 not found

[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:09] WARNING: not removing hydrogen atom without neighbors
[16:19:10] Explicit valence for atom # 7 Br, 3, is greater than permitted
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] Explicit valence for atom # 26 Cl, 3, is greater than permitted
[16:19:10] Explicit valence for atom # 47 Cl, 3, is greater than permitted
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors
[16:19:10] WARNING: not removing hydrogen atom without neighbors

CIDs05311033 not found

[16:19:10] Explicit valence for atom # 1 Cl, 3, is greater than permitted
[16:19:10] Explicit valence for atom # 7 Cl, 5, is greater than permitted
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors
[16:19:11] WARNING: not removing hydrogen atom without neighbors

CIDs00449974 not found

[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] Explicit valence for atom # 25 Cl, 3, is greater than permitted
[16:19:12] Explicit valence for atom # 26 Cl, 3, is greater than permitted
[16:19:12] Explicit valence for atom # 44 Cl, 3, is greater than permitted
[16:19:12] Explicit valence for atom # 10 Cl, 3, is greater than permitted
[16:19:12] Explicit valence for atom # 10 Cl, 3, is greater than permitted
[16:19:12] Explicit valence for atom # 21 Cl, 3, is greater than permitted
[16:19:12] Explicit valence for atom # 18 Cl, 3, is greater than permitted
[16:19:12] Explicit valence for atom # 22 Cl, 3, is greater than permitted
[16:19:12] Explicit valence for atom # 25 Cl, 3, is greater than permitted
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:12] WARNING: not removing hydrogen atom without neighbors
[16:19:13] Explicit valence for atom # 1 Cl, 2, is greater than permitted
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] Explicit valence for atom # 1 I, 7, is greater than permitted
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] Explicit valence for atom # 1 Br, 3, is greater than permitted
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] Explicit valence for atom # 1 Si, 8, is greater than permitted
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] WARNING: not removing hydrogen atom without neighbors
[16:19:13] Explicit valence for atom # 1 Si, 8, is greater than permitted
[16:19:13] Explicit valence for atom # 1 Si, 8, is greater than permitted
[16:19:13] Explicit valence for atom # 1 Si, 8, is greater than permitted
[16:19:14] WARNING: not removing hydrogen atom without neighbors
[16:19:14] WARNING: not removing hydrogen atom without neighbors
[16:19:14] Explicit valence for atom # 1 Cl, 3, is greater than permitted
[16:19:14] Explicit valence for atom # 1 Br, 5, is greater than permitted
[16:19:14] Explicit valence for atom # 1 Br, 3, is greater than permitted
[16:19:14] WARNING: not removing hydrogen atom without neighbors
[16:19:14] Explicit valence for atom # 1 Cl, 7, is greater than permitted
[16:19:14] WARNING: not removing hydrogen atom without neighbors

In [84]:
compound_embeddings = kamping.get_mol_embeddings_from_dataframe(ROMols, transformer='morgan')

WARNING:root:Successfully parse 786444 rows with valid SMILES from the MOL file!
'
                    total 0 Invalid rows with "None" in the ROMol column
WARNING:root: [], removed from the final output!

In [85]:
# save the embeddings using h5py
import h5py
with h5py.File('../data/string_stitch/raw/compound_embeddings.h5', 'w') as f:
    for key, value in compound_embeddings.items():
        f.create_dataset(key, data=value)

In [86]:
compound_embeddings

{'CIDm91758680': array([0., 0., 0., ..., 0., 0., 1.], dtype=float32),
 'CIDm91758408': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91758407': array([0., 0., 0., ..., 0., 1., 0.], dtype=float32),
 'CIDm91758406': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91758404': array([0., 1., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91758403': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91758402': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91758401': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91758389': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91758271': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757967': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757966': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757965': array([0., 1., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757964': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757962': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757960': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757948': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757947': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757946': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757945': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757944': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757941': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757938': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757937': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91757705': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754990': array([0., 0., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754987': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754984': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754983': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754982': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754981': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754979': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754977': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754976': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754975': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754974': array([0., 0., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754972': array([0., 0., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754971': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754969': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754964': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754961': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754958': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754956': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754955': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754953': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754952': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754951': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754946': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754711': array([0., 0., 0., ..., 1., 0., 0.], dtype=float32),
 'CIDm91754604': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754603': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754602': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754600': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754581': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754554': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754243': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754234': array([1., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754232': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754231': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754228': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91754227': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91753580': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91753435': array([0., 0., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91753270': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91751258': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91751196': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91751184': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91751164': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91750293': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91750195': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91750039': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91748033': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91747900': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91747166': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91746572': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91746550': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91746481': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91746378': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91746331': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91746319': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91746317': array([0., 1., 0., ..., 1., 0., 0.], dtype=float32),
 'CIDm91746315': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91746314': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91746313': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91746312': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91746311': array([0., 1., 0., ..., 0., 1., 0.], dtype=float32),
 'CIDm91746295': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91746294': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91739162': array([0., 0., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91727408': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91716943': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91710915': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91699622': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91692905': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668558': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668557': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668556': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668555': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668554': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668553': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668551': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668550': array([1., 1., 0., ..., 1., 0., 0.], dtype=float32),
 'CIDm91668545': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668544': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668543': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668540': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668539': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668532': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668531': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668528': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91668184': array([0., 1., 0., ..., 0., 1., 0.], dtype=float32),
 'CIDm91667932': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667928': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667926': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667715': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667430': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667429': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667428': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667421': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667420': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667415': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667414': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667413': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667412': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667411': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667409': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667408': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667406': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667405': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667404': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91667403': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666471': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666469': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666468': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666467': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666466': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666463': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666459': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666458': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666457': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666456': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666445': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666347': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666345': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666322': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666319': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91666313': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91665256': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91664024': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91664020': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91664017': array([0., 1., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91664013': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91664012': array([0., 1., 0., ..., 0., 0., 1.], dtype=float32),
 'CIDm91664007': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91664002': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91663465': array([1., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91663464': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91663444': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91663443': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91663437': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91663271': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91663255': array([1., 0., 0., ..., 0., 0., 1.], dtype=float32),
 'CIDm91663192': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91663129': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91632909': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91623344': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91623334': array([0., 0., 0., ..., 0., 1., 0.], dtype=float32),
 'CIDm91623329': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91623327': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91623326': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91623324': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91623323': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91623020': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91620187': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91617971': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91617630': array([0., 0., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91616559': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91616435': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91616422': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91616358': array([0., 0., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91615522': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91614560': array([0., 1., 0., ..., 0., 1., 0.], dtype=float32),
 'CIDm91614073': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91613579': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91613561': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91612801': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91612599': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91612275': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91611974': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91610865': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91610072': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91609726': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91609326': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91609320': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91609169': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91609041': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91608615': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91608456': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91608251': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91607816': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91607805': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91607520': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91606547': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91606271': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91605851': array([1., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91605615': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91605236': array([0., 0., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91604364': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91604360': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91604268': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91603822': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91603774': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91603583': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91603096': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91602940': array([0., 1., 0., ..., 1., 0., 0.], dtype=float32),
 'CIDm91602719': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91602368': array([0., 0., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91602281': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91602122': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91601132': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91600427': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91599644': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91598531': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91598375': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91597903': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91597553': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91596862': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91596607': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91596579': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91596373': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91596222': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91596152': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91595832': array([0., 0., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91595650': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91595371': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91594590': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91594409': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91594181': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91593217': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91592988': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91592865': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91592643': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91592640': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91592353': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91591100': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91589696': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91589650': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91589147': array([0., 1., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91588933': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91588676': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91588540': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91588518': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91588270': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91587773': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91587673': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91587001': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91586643': array([1., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91586532': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91586143': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91585947': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91585844': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91585581': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91585382': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91583236': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91582920': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91582556': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91582319': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91582103': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91581925': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91581757': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91581619': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91581576': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91581403': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91581049': array([0., 0., 1., ..., 0., 0., 0.], dtype=float32),
 'CIDm91580835': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91580413': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91580072': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91580014': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91579984': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91579755': array([0., 1., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91579718': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91579387': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91578871': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91578553': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 'CIDm91578497': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),

# Convert string to Uniprot ID

In [53]:
uniprot_df = pd.read_table('/Users/cgu3/Documents/Grape-Pi/data/miscellaneous/uniprotkb_proteome_UP000005640_AND_revi_2023_10_05.tsv', sep='\t')
uniprot_df = uniprot_df[['STRING', 'Entry']]
uniprot_df.dropna(subset=['STRING'], inplace=True)
uniprot_df['STRING'] = uniprot_df['STRING'].str.replace(';', '')
uniprot_df

                     STRING       Entry
2      9606.ENSP00000482829  A0A0B4J2F2
7      9606.ENSP00000377112      A0AV02
8      9606.ENSP00000371212      A0AV96
9      9606.ENSP00000419279      A0AVF1
10     9606.ENSP00000372394      A0AVI4
...                     ...         ...
20371  9606.ENSP00000429608      Q96PS1
20373  9606.ENSP00000402355      Q96T59
20383  9606.ENSP00000359558      Q9H1L0
20388  9606.ENSP00000455079      Q9H693
20394  9606.ENSP00000418086      Q9HBI5

[18528 rows x 2 columns]

In [60]:
mpi = pd.read_csv('../data/string_stitch/raw/9606.protein_chemical.links.v5.0.tsv', sep='\t')
mpi

              chemical               protein  combined_score
0         CIDm91758680  9606.ENSP00000257254             279
1         CIDm91758680  9606.ENSP00000302120             154
2         CIDm91758408  9606.ENSP00000006777             225
3         CIDm91758408  9606.ENSP00000056217             178
4         CIDm91758408  9606.ENSP00000216085             225
...                ...                   ...             ...
15473934  CIDs00000001  9606.ENSP00000420588             151
15473935  CIDs00000001  9606.ENSP00000436585             279
15473936  CIDs00000001  9606.ENSP00000438144             311
15473937  CIDs00000001  9606.ENSP00000448165             322
15473938  CIDs00000001  9606.ENSP00000453129             197

[15473939 rows x 3 columns]

In [61]:
mpi['protein'] = kamping.utils.mapping(mpi['protein'], uniprot_df, na_rm=False)
# drop the rows with missing values
mpi.dropna(subset=['protein'], inplace=True)

In [64]:
mpi.to_csv('../data/string_stitch/raw/9606.protein_chemical_translated.links.v5.0.tsv', sep='\t', index=False)

# Use dataset to create a graph from the data

In [87]:
MetaboliteProteinInteraction(root='../data/string_stitch')

Processing...
/Users/cgu3/Documents/experiments/KAMPING/kamping/data/convert.py:324: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  hetero_data_dict[group][key] = torch.tensor(value)
Done!
/Users/cgu3/Documents/experiments/KAMPING/kamping/data/dataset.py:16: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.

MetaboliteProteinInteraction()